### ISSUE TITLE
Import Worship Him 1.0.7.8 database fails (java.io.IOException)

### ISSUE THREAD

**Issue by DeeTigIT** [quelea-projection/Quelea#273]
The current Worship Him (https://www.worship-him.com/) importer fails to import Worship Him 1.0.7.8 database (MySongsPE.mdb).

![S1](https://user-images.githubusercontent.com/39883796/89105325-6e223900-d420-11ea-9d9c-3e55d5b2398b.JPG)

Debuglog fragment:

java.io.IOException: Did not find required parent table id (Db=MySongsPE.mdb)
        at com.healthmarketscience.jackcess.impl.DatabaseImpl.readSystemCatalog(DatabaseImpl.java:996)
        at com.healthmarketscience.jackcess.impl.DatabaseImpl.<init>(DatabaseImpl.java:556)
        at com.healthmarketscience.jackcess.impl.DatabaseImpl.open(DatabaseImpl.java:415)
        at com.healthmarketscience.jackcess.DatabaseBuilder.open(DatabaseBuilder.java:267)
        at org.quelea.services.importexport.WorshipHimParser.getSongs(WorshipHimParser.java:58)
        at org.quelea.services.importexport.ImportDialog$1.run(ImportDialog.java:201)

tested with release : Quelea 2020.0 B2 (cross-platform)

**Comment by dsfb** [comment]
Hi, @berry120!
Can I help the Quelea project by trying to solve this issue, please?
Obs.: It will be my first Oktoberfest issue!

**Comment by berry120** [comment]
@dsfb Sure, all yours! Any questions just ask.

**Comment by dsfb** [comment]
Thanks, @berry120!
And I am sorry for this!

**Comment by berry120** [comment]
@DeeTigIT This should now work in the latest CI release.

**Comment by DeeTigIT** [comment]
Indeed, thanks!
