### ISSUE TITLE
Q2021 Beta crashes on start

### ISSUE THREAD

**Issue by leealex** [quelea-projection/Quelea#362]
Macbook Pro 16"
Mac OS Big Sur 11.4

Today i've downloaded last build and managed to launch it one time, after changing settings of the screens I saved them and restarted the app. After that I cant launch Quelea. I also tried Q2020 stable release.

Here's log:

```Leealex:~ leealex$ /Users/leealex/Downloads/Quelea\ 2.app/Contents/MacOS/Quelea ; exit;
июн 12, 2021 2:31:47 PM org.quelea.services.languages.LabelGrabber <init>
INFO: Using languages file /Users/leealex/Downloads/Quelea 2.app/Contents/Resources/languages/ru.lang
июн 12, 2021 2:31:47 PM org.quelea.services.languages.LabelGrabber <init>
INFO: Setting en locale
Jun 12, 2021 2:31:47 PM org.quelea.services.languages.LabelGrabber <init>
INFO: Using english language file as backup
Jun 12, 2021 2:31:47 PM org.quelea.windows.main.Main start
INFO: Started, version 2021.0
Jun 12, 2021 2:31:47 PM org.quelea.windows.main.Main start
INFO: OS name: Mac OS X
Jun 12, 2021 2:31:47 PM org.quelea.windows.main.Main start
INFO: Using JAVA version 1.8.0_281
Jun 12, 2021 2:31:47 PM org.quelea.windows.main.Main start
INFO: 64-bit: true
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Jun 12, 2021 2:31:47 PM org.quelea.windows.multimedia.MacVideo$1 run
INFO: Video initialised ok
Jun 12, 2021 2:31:48 PM org.quelea.services.utils.FontInstaller lambda$setupBundledFonts$0
INFO: Loaded bundled font /Users/leealex/Downloads/Quelea 2.app/Contents/Resources/icons/bundledfonts/UbuntuMono-BoldItalic.ttf
Jun 12, 2021 2:31:48 PM org.quelea.services.utils.FontInstaller lambda$setupBundledFonts$0
INFO: Loaded bundled font /Users/leealex/Downloads/Quelea 2.app/Contents/Resources/icons/bundledfonts/LiberationSans-Bold.ttf
Jun 12, 2021 2:31:48 PM org.quelea.services.utils.FontInstaller lambda$setupBundledFonts$0
INFO: Loaded bundled font /Users/leealex/Downloads/Quelea 2.app/Contents/Resources/icons/bundledfonts/LiberationSans-BoldItalic.ttf
Jun 12, 2021 2:31:48 PM org.quelea.services.utils.FontInstaller lambda$setupBundledFonts$0
INFO: Loaded bundled font /Users/leealex/Downloads/Quelea 2.app/Contents/Resources/icons/bundledfonts/UbuntuMono-Bold.ttf
Jun 12, 2021 2:31:48 PM org.quelea.services.utils.FontInstaller lambda$setupBundledFonts$0
INFO: Loaded bundled font /Users/leealex/Downloads/Quelea 2.app/Contents/Resources/icons/bundledfonts/Vegur-Bold.otf
Jun 12, 2021 2:31:48 PM org.quelea.services.utils.FontInstaller lambda$setupBundledFonts$0
INFO: Loaded bundled font /Users/leealex/Downloads/Quelea 2.app/Contents/Resources/icons/bundledfonts/RobotoMono-Regular.ttf
Jun 12, 2021 2:31:48 PM org.quelea.services.utils.FontInstaller lambda$setupBundledFonts$0
INFO: Loaded bundled font /Users/leealex/Downloads/Quelea 2.app/Contents/Resources/icons/bundledfonts/RobotoMono-BoldItalic.ttf
Jun 12, 2021 2:31:48 PM org.quelea.services.utils.FontInstaller lambda$setupBundledFonts$0
INFO: Loaded bundled font /Users/leealex/Downloads/Quelea 2.app/Contents/Resources/icons/bundledfonts/Oxygen-Bold.otf
Jun 12, 2021 2:31:48 PM org.quelea.services.utils.FontInstaller lambda$setupBundledFonts$0
INFO: Loaded bundled font /Users/leealex/Downloads/Quelea 2.app/Contents/Resources/icons/bundledfonts/UbuntuMono-Italic.ttf
Jun 12, 2021 2:31:48 PM org.quelea.services.utils.FontInstaller lambda$setupBundledFonts$0
INFO: Loaded bundled font /Users/leealex/Downloads/Quelea 2.app/Contents/Resources/icons/bundledfonts/Oxygen-Italic.otf
Jun 12, 2021 2:31:48 PM org.quelea.services.utils.FontInstaller lambda$setupBundledFonts$0
INFO: Loaded bundled font /Users/leealex/Downloads/Quelea 2.app/Contents/Resources/icons/bundledfonts/UbuntuMono-Regular.ttf
Jun 12, 2021 2:31:48 PM org.quelea.services.utils.FontInstaller lambda$setupBundledFonts$0
INFO: Loaded bundled font /Users/leealex/Downloads/Quelea 2.app/Contents/Resources/icons/bundledfonts/LiberationSans-Italic.ttf
Jun 12, 2021 2:31:48 PM org.quelea.services.utils.FontInstaller lambda$setupBundledFonts$0
INFO: Loaded bundled font /Users/leealex/Downloads/Quelea 2.app/Contents/Resources/icons/bundledfonts/RobotoMono-Bold.ttf
Jun 12, 2021 2:31:48 PM org.quelea.services.utils.FontInstaller lambda$setupBundledFonts$0
INFO: Loaded bundled font /Users/leealex/Downloads/Quelea 2.app/Contents/Resources/icons/bundledfonts/Oxygen-BoldItalic.otf
Jun 12, 2021 2:31:48 PM org.quelea.services.utils.FontInstaller lambda$setupBundledFonts$0
INFO: Loaded bundled font /Users/leealex/Downloads/Quelea 2.app/Contents/Resources/icons/bundledfonts/RobotoMono-Italic.ttf
Jun 12, 2021 2:31:48 PM org.quelea.services.utils.FontInstaller lambda$setupBundledFonts$0
INFO: Loaded bundled font /Users/leealex/Downloads/Quelea 2.app/Contents/Resources/icons/bundledfonts/LiberationSans-Regular.ttf
Jun 12, 2021 2:31:48 PM org.quelea.services.utils.FontInstaller lambda$setupBundledFonts$0
INFO: Loaded bundled font /Users/leealex/Downloads/Quelea 2.app/Contents/Resources/icons/bundledfonts/Oxygen.otf
Jun 12, 2021 2:31:48 PM org.quelea.services.utils.FontInstaller lambda$setupBundledFonts$0
INFO: Loaded bundled font /Users/leealex/Downloads/Quelea 2.app/Contents/Resources/icons/bundledfonts/Vegur-Regular.otf
Jun 12, 2021 2:31:48 PM org.quelea.services.utils.UserFileChecker checkUserFiles
INFO: Checking user files
Jun 12, 2021 2:31:48 PM org.quelea.windows.main.Main$1 run
INFO: Number of displays: 1
Jun 12, 2021 2:31:48 PM org.quelea.windows.main.Main$1 run
INFO: Starting lyric server on 1,111
Jun 12, 2021 2:31:48 PM org.quelea.windows.main.Main$1 run
INFO: Starting remote control server on 1,112
Jun 12, 2021 2:31:48 PM org.quelea.windows.main.Main$1 run
INFO: Starting auto-detection server on 50,015
Jun 12, 2021 2:31:48 PM org.quelea.windows.main.Main$1 run
INFO: Starting projector display: 
Jun 12, 2021 2:31:48 PM org.quelea.windows.main.Main$1 run
INFO: Hiding stage display on monitor 0 (base 0!)
Jun 12, 2021 2:31:48 PM org.quelea.windows.main.Main$1 lambda$run$8
INFO: Loading bibles
Jun 12, 2021 2:31:48 PM org.quelea.data.db.HibernateUtil init
INFO: Initialising hibernate
Jun 12, 2021 2:31:48 PM org.quelea.data.bible.Bible parseBible
INFO: Parsing bible: /Users/leealex/.quelea/bibles/Russian Synodal.xml
Jun 12, 2021 2:31:49 PM org.quelea.services.utils.Utils getEncoding
INFO: Detected UTF-8 encoding for /Users/leealex/.quelea/bibles/Russian Synodal.xml
Jun 12, 2021 2:31:49 PM org.hibernate.annotations.common.reflection.java.JavaReflectionManager <clinit>
INFO: HCANN000001: Hibernate Commons Annotations {4.0.5.Final}
Jun 12, 2021 2:31:49 PM org.hibernate.Version logVersion
INFO: HHH000412: Hibernate Core {4.3.11.Final}
Jun 12, 2021 2:31:49 PM org.hibernate.cfg.Environment <clinit>
INFO: HHH000206: hibernate.properties not found
Jun 12, 2021 2:31:49 PM org.hibernate.cfg.Environment buildBytecodeProvider
INFO: HHH000021: Bytecode provider name : javassist
Jun 12, 2021 2:31:49 PM org.quelea.data.db.HibernateUtil init
INFO: Initialised hibernate properties
Jun 12, 2021 2:31:49 PM org.quelea.data.db.HibernateUtil init
INFO: Initialised hibernate service registry
Jun 12, 2021 2:31:49 PM org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl configure
WARN: HHH000402: Using Hibernate built-in connection pool (not for production use!)
Jun 12, 2021 2:31:49 PM org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl buildCreator
INFO: HHH000401: using driver [org.hsqldb.jdbcDriver] at URL [jdbc:hsqldb:/Users/leealex/.quelea/database_new/database_new]
Jun 12, 2021 2:31:49 PM org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl buildCreator
INFO: HHH000046: Connection properties: {dialect=org.hibernate.dialect.HSQLDialect, characterEncoding=utf8}
Jun 12, 2021 2:31:49 PM org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl buildCreator
INFO: HHH000006: Autocommit mode: false
Jun 12, 2021 2:31:49 PM org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl configure
INFO: HHH000115: Hibernate connection pool size: 20 (min=1)
Jun 12, 2021 2:31:50 PM org.quelea.windows.main.Main$UncaughtExceptionHandler uncaughtException
SEVERE: Uncaught exception on thread: JavaFX Application Thread
java.lang.IllegalArgumentException: No enum constant org.quelea.data.displayable.TextAlignment.REPORT AN ISSUE
	at java.lang.Enum.valueOf(Enum.java:238)
	at org.quelea.data.displayable.TextAlignment.valueOf(TextAlignment.java:27)
	at org.quelea.services.utils.QueleaProperties.getStageTextAlignment(QueleaProperties.java:889)
	at org.quelea.windows.options.OptionsStageViewPanel.<init>(OptionsStageViewPanel.java:67)
	at org.quelea.windows.options.PreferencesDialog.<init>(PreferencesDialog.java:88)
	at org.quelea.windows.main.MainWindow.<init>(MainWindow.java:92)
	at org.quelea.windows.main.Main$1.lambda$run$10(Main.java:243)
	at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)

Jun 12, 2021 2:31:50 PM org.quelea.windows.main.Main$UncaughtExceptionHandler uncaughtException
SEVERE: Uncaught exception on thread: JavaFX Application Thread
java.lang.NullPointerException
	at org.quelea.windows.main.Main$1.lambda$run$12(Main.java:252)
	at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)

Jun 12, 2021 2:31:50 PM org.quelea.windows.main.Main$UncaughtExceptionHandler uncaughtException
SEVERE: Uncaught exception on thread: JavaFX Application Thread
java.lang.NullPointerException
	at org.quelea.services.utils.ShortcutManager.addShortcuts(ShortcutManager.java:50)
	at org.quelea.windows.main.Main$1.lambda$run$13(Main.java:271)
	at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)

Jun 12, 2021 2:31:50 PM org.quelea.windows.main.Main$UncaughtExceptionHandler uncaughtException
SEVERE: Uncaught exception on thread: JavaFX Application Thread
java.lang.NullPointerException
	at org.quelea.windows.main.Main$1.lambda$run$17(Main.java:306)
	at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)

logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

```

**Comment by leealex** [comment]
Hi, @berry120 is there way to fix it by myself? Reinstall Java or something else?

**Comment by ArvidNy** [comment]
My guess, without looking too closely at the log, is that you are using the cross-platform version(?) and a Java version that has introduced changes that we haven't added fixes for yet. In that case, my suggestion would be to try to either downgrade the Java version or use the Mac installer instead and see if that helps.

**Comment by PaulD987** [comment]
@leealex can you look in the quelea.properties file (in your home directory .quelea/quelea.properties), and see if you have stage.text.alignment set, and if so, paste the line in here... for example, this is what mine has:
```
stage.text.alignment=CENTRE
```
I suspect that there may be an unexpected value for that property.

If not sure how to get the properties, open a terminal and enter this:
```
grep stage.text.alignment ~/.quelea/quelea.properties 
```

**Comment by leealex** [comment]
> @leealex can you look in the quelea.properties file (in your home directory .quelea/quelea.properties), and see if you have stage.text.alignment set, and if so, paste the line in here... for example, this is what mine has:
> 
> ```
> stage.text.alignment=CENTRE
> ```
> 
> I suspect that there may be an unexpected value for that property.
> 
> If not sure how to get the properties, open a terminal and enter this:
> 
> ```
> grep stage.text.alignment ~/.quelea/quelea.properties 
> ```

`stage.text.alignment=REPORT AN ISSUE`

**Comment by leealex** [comment]
Thank you @PaulD987 !!! I changed the value to `CENTRE` and now Quelea managed to start successfully! 
You made my day, man ))

**Comment by PaulD987** [comment]
Yep, that makes sense!! I thought it would be that, after having taken another look after the message I posted earlier. if you change it to what I have, eg CENTRE, then I suspect it will start working again. That however doesn't explain how it got set to that value in the first place! I was wondering if it was something to do with you using the Russian language pack, but I can't recreate the failure on my machine. "REPORT AN ISSUE" is the value for remote.report.issue, but I can't actually see that being used anywhere, and doesn't exist in the Russian language files. So I'm at a lose to explain how it got set to that. Maybe @berry120 will have an idea!

**Comment by leealex** [comment]
As I remember, it happened after I've changed Projector screen settings. After saving settings Quelea couldn't start anymore. I'll try to reproduce it.

**Comment by berry120** [comment]
@leealex Just checking if you ever managed to reproduce this one?

**Comment by leealex** [comment]
@berry120 Nope 🤷‍♂️

**Comment by berry120** [comment]
No worries. Let's close it off for now and feel free to re-open if you're able to reproduce, then we'll look at fixing it 👍
