### ISSUE TITLE
Error message loading bible still refers to quelea googlegroups

### ISSUE THREAD

**Issue by DeeTigIT** [quelea-projection/Quelea#513]
Error message loading bible still refers to quelea googlegroups (instead of https://quelea.discourse.group/).

![S1](https://user-images.githubusercontent.com/39883796/140639217-4ebe912c-d922-4fed-bdd5-1efe7af9b335.JPG)

**Comment by berry120** [comment]
Hey, is this the same in the CI release as well? I feel like this is sorted as we removed the functionality to upload files for analysis (and so fixed that at the same time) but I could be mistaken.

**Comment by DeeTigIT** [comment]
In the latest CI as well : the literal "quelea-discuss@googlegroups.com".

![S1](https://user-images.githubusercontent.com/39883796/140654307-c38abb17-b5cf-4a7e-93f2-7e63e587f476.JPG)

**Comment by berry120** [comment]
Hmm, are you sure it's definitely this release that you're using? (https://github.com/quelea-projection/Quelea/releases/tag/CI-RELEASE) - I've just grabbed it but don't see that message at all.

**Comment by DeeTigIT** [comment]
You are right here, I did the test with the wrong Quelea runtime. 

With the latest CI cross-platform version:
- importing an erronious bible-xml file: 
-- no error message pop-up is given
-- the bible is added to the c:\Users\<account>\.quelea\bibles\
-- the command box reports a fatal error: see Appendix 1)
-- The erronious bible can't be selected in Quelea.
- closing Quelea and restart:
-- no error message pop-up is given
-- the command box reports a fatal error: see Appendix 2)
-- The erronious bible can't be selected in Quelea.

I'm using:
- Quelea CI-RELEASE 2022.0 cross-platform
- OpenJDK11U-jre_x64_windows_hotspot_11.0.12_7.msi (Adoptium Eclipse Temurin)

Does the latest CI Windows version perhaps uses a message pop-up? (I didn't test that)

Appendix 1)

[Fatal Error] :1314:5: The element type "CHAPTER" must be terminated by the matching end-tag "</CHAPTER>".
2021-11-08T20:19:34.179+0100  WARNING  Couldn't parse the bible C:\Users\account\.quelea\bibles\SF_2017-11-16_DE_LEO_RP05_(LEONBERGER BIBEL (RP05)) - error.xml
org.xml.sax.SAXParseException; lineNumber: 1314; columnNumber: 5; The element type "CHAPTER" must be terminated by the matching end-tag "</CHAPTER>".
        at java.xml/com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(Unknown Source)
        at java.xml/com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(Unknown Source)
        at org.quelea.data.bible.Bible.parseBible(Bible.java:120)
        at org.quelea.data.bible.BibleManager.loadBibles(BibleManager.java:166)
        at org.quelea.data.bible.BibleManager.refreshAndLoad(BibleManager.java:146)
        at org.quelea.windows.options.customprefs.DefaultBibleSelector.lambda$createAddBibleButton$6(DefaultBibleSelector.java:144)
        at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
        at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
        at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
        at javafx.event.Event.fireEvent(Event.java:198)
        at javafx.scene.Node.fireEvent(Node.java:8792)
        at javafx.scene.control.Button.fire(Button.java:203)
        at com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:208)
        at com.sun.javafx.scene.control.inputmap.InputMap.handle(InputMap.java:274)
        at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:247)
        at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
        at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
        at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
        at javafx.event.Event.fireEvent(Event.java:198)
        at javafx.scene.Scene$MouseHandler.process(Scene.java:3897)
        at javafx.scene.Scene.processMouseEvent(Scene.java:1878)
        at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2623)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:411)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:301)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:450)
        at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:424)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:449)
        at com.sun.glass.ui.View.handleMouseEvent(View.java:557)
        at com.sun.glass.ui.View.notifyMouse(View.java:943)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:184)
        at java.base/java.lang.Thread.run(Unknown Source)

Appendix 2)

[Fatal Error] :1314:5: The element type "CHAPTER" must be terminated by the matching end-tag "</CHAPTER>".
Nov 08, 2021 8:24:05 PM org.quelea.data.bible.Bible parseBible
WARNING: Couldn't parse the bible C:\Users\account\.quelea\bibles\SF_2017-11-16_DE_LEO_RP05_(LEONBERGER BIBEL (RP05)) - error.xml
org.xml.sax.SAXParseException; lineNumber: 1314; columnNumber: 5; The element type "CHAPTER" must be terminated by the matching end-tag "</CHAPTER>".
        at java.xml/com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(Unknown Source)
        at java.xml/com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(Unknown Source)
        at org.quelea.data.bible.Bible.parseBible(Bible.java:120)
        at org.quelea.data.bible.BibleManager.loadBibles(BibleManager.java:166)
        at org.quelea.data.bible.BibleManager.<init>(BibleManager.java:60)
        at org.quelea.data.bible.BibleManager.<clinit>(BibleManager.java:44)
        at org.quelea.windows.main.Main$1.lambda$run$8(Main.java:232)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)

**Comment by berry120** [comment]
Should now be fixed in the CI release - thanks for reporting!

**Comment by berry120** [comment]
Sorry, mixed up the messages - ignore me!

**Comment by berry120** [comment]
Ok, so this should now be fixed (properly this time.)

I think the only bit of the behaviour there that I don't agree with is the silent failure when an invalid bible is added - we should display a message saying it's invalid and *not* copy it across to the bibles directory which should now happen.

Corrupt files already in the folder will throw an exception silently when Quelea tries to load them, but I think I'll leave that as-is - they're not really doing any harm there and the only other thing we could do is try to delete them automatically if they're corrupt, which isn't something I really want to get into (if it goes wrong and deletes a valid bible, that wouldn't be so great!)

**Comment by DeeTigIT** [comment]
Thanks for solving!

- Loading a new, invalid xml-bible:

![S1](https://user-images.githubusercontent.com/39883796/143669513-0a323b55-2c15-4529-8d56-7fe482600cc9.JPG)

The erroneuous xml-bible is not copied to the .quelea\bibles folder.

- An invalid xml-bible (manually placed) .quelea\bibles folder

Throws an exception silently when Quelea tries to load it.

[Fatal Error] :1314:5: The element type "CHAPTER" must be terminated by the matching end-tag "</CHAPTER>".
2021-11-27T06:40:13.180+0100  WARNING  Couldn't parse the bible C:\Users\AccountNameHere\.quelea\bibles\SF_2017-11-16_DE_LEO_RP05_(LEONBERGER BIBEL (RP05)) - error.xml
org.xml.sax.SAXParseException; lineNumber: 1314; columnNumber: 5; The element type "CHAPTER" must be terminated by the matching end-tag "</CHAPTER>".
        at java.xml/com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(Unknown Source)
        at java.xml/com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(Unknown Source)
        at org.quelea.data.bible.Bible.parseBible(Bible.java:120)
        at org.quelea.data.bible.BibleManager.loadBibles(BibleManager.java:166)
        at org.quelea.data.bible.BibleManager.<init>(BibleManager.java:60)
        at org.quelea.data.bible.BibleManager.<clinit>(BibleManager.java:44)
        at org.quelea.windows.main.Main$1.lambda$run$8(Main.java:232)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)

2021-11-27T06:40:16.491+0100  WARNING  Cant get notice from folder: {0}

I'm using:

    Quelea CI-RELEASE 2022.0 cross-platform
    OpenJDK11U-jre_x64_windows_hotspot_11.0.12_7.msi (Adoptium Eclipse Temurin)
