### ISSUE TITLE
Attempt auto translation not working

### ISSUE THREAD

**Issue by Youngwily** [quelea-projection/Quelea#541]
Auto translation option is checked in Options but does not work, the database log shows this info:

Apr 07, 2022 2:13:26 PM org.quelea.windows.lyrics.TranslatePanel getTranslatedLyrics
INFO: Error translating
java.lang.Exception: [microsoft-translator-api] Error retrieving translation : datamarket.accesscontrol.windows.net
	at com.memetix.mst.MicrosoftTranslatorAPI.retrieveString(MicrosoftTranslatorAPI.java:202)
	at com.memetix.mst.detect.Detect.execute(Detect.java:55)
	at org.quelea.windows.lyrics.TranslatePanel.getTranslatedLyrics(TranslatePanel.java:220)
	at org.quelea.windows.lyrics.TranslatePanel$1$1.run(TranslatePanel.java:98)
Caused by: java.net.UnknownHostException: datamarket.accesscontrol.windows.net
	at java.base/java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
	at java.base/java.net.Socket.connect(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.connect(Unknown Source)
	at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(Unknown Source)
	at java.base/sun.net.NetworkClient.doConnect(Unknown Source)
	at java.base/sun.net.www.http.HttpClient.openServer(Unknown Source)
	at java.base/sun.net.www.http.HttpClient.openServer(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsClient.New(Unknown Source)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(Unknown Source)
	at com.memetix.mst.MicrosoftTranslatorAPI.getToken(MicrosoftTranslatorAPI.java:133)
	at com.memetix.mst.MicrosoftTranslatorAPI.retrieveResponse(MicrosoftTranslatorAPI.java:160)
	at com.memetix.mst.MicrosoftTranslatorAPI.retrieveString(MicrosoftTranslatorAPI.java:199)
	... 3 more

**Comment by berry120** [comment]
Auto-translation is using an old API that's since long been deprecated - it's just something we've never got around to removing I'm afraid. This isn't something we're likely to put the engineering effort in to re-implement unless we can confirm a significant number of people are actually using it (which I don't think they are, it was always more of a fringe feature that I'm never sure saw much use.)

If that's not the case and we get a number of people posting here saying it's valuable for them, then we'll take another look 👍

**Comment by Youngwily** [comment]
Fair enough 👍

**Comment by berry120** [comment]
Closing this one off as it's not something we can realistically support.
